opening_title: Demo: Postman 101
opening_image: images/consumers.png

closing_title: Demo: Postman 101
closing_image: integrations_postmanaut_4.png

markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
